import type { NextPage } from 'next'
import Head from 'next/head'
import albumsJSON from '@common/asset/albums.json'
import type { Album, AlbumType, AlbumTrackRef } from '@src/common/asset/mla'

const albums: Array<Album> = albumsJSON as Array<Album>

const AdminAlbums: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <table>
        {albums.map((album: Album, idx: number) => {
          const {name, slug, type, edition, track_no, tracks} = album
          return (
            <tr>
              <td>
                {name}<br/>
                {slug}
              </td>
              <td>
                {type}
              </td>
              <td>
                {edition}
              </td>
              <td>
                {track_no}
              </td>
              <td style={{whiteSpace: 'pre-wrap'}}>
                {tracks.map((aList: AlbumTrackRef, _i: number) => 
                  `${_i+1}: ${aList.name}\n`
                )}
              </td>
            </tr>
          )
        })}
      </table>
    </div>
  )
}

export default AdminAlbums