import type { NextPage } from 'next'
import Head from 'next/head'
import albumsJSON from '@common/asset/albums.json'
import tracks from '@common/asset/tracks.json'
import { MouseEvent, useState } from 'react'
import type { Album, AlbumType, AlbumTrackRef, Track } from '@src/common/asset/mla'
import styles from '@styles/admin.module.sass'

const albums: Array<Album> = albumsJSON as Array<Album>

const AdminAlbums: NextPage = () => {
  const [selected, setSelected] = useState<string | null>(null)

  const selectTrack = (slug: string) => (e: MouseEvent<HTMLButtonElement>) => {
    setSelected(slug)
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.root}>
        <aside>
          <ul>
            {tracks.map((track: Track, idx: number) => 
              <li>
                <button onClick={selectTrack(track.slug)}>
                  {track.name}
                </button>
              </li>
            )}
          </ul>
        </aside>

        <div>
          {selected && 
            <div>
              {tracks.find(_t => _t.slug === selected)?.name}
            </div>
          }
        </div>
      </div>
    </>
  )
}

export default AdminAlbums